package:
  id: SAP_SMOKE_TEST
  name: SAP Smoke Test
  version: 1.0.0
  template: ../artifacts/SAP_SMOKE_TEST_PACKAGE.zip

flow:
  id: SAP_SMOKE_TEST_FLOW
  name: SAP Smoke Test Flow
  version: 1.0.0
  template: ../artifacts/SAP_SMOKE_TEST_FLOW.zip
  configuration: {}

deployment:
  poll_seconds: 5
  timeout_seconds: 300
