name: Deploy SAP Cloud Integration flow
run-name: Deploy SAP Cloud Integration flow - ${{ inputs.operation || 'update' }}-${{ inputs.version || '1.0.1' }}

on:
  workflow_dispatch:
    inputs:
      operation:
        description: "Upload a new artifact or update an existing artifact"
        required: true
        default: update
        type: choice
        options: [update, upload]
      version:
        description: "New CPI semantic version"
        required: true
        default: 1.0.1
        type: string
jobs:
  sdlc:
    uses: ./.github/workflows/sap-cpi-sdlc.yml
    with:
      manifest: config/SAP_SMOKE_TEST.yaml
      source: flows/SAP_SMOKE_TEST_FLOW
      bundle: SAP_SMOKE_TEST_FLOW.zip
      artifact_id: SAP_SMOKE_TEST_FLOW
      operation: ${{ inputs.operation || 'update' }}
      version: ${{ inputs.version || '1.0.1' }}
    secrets: inherit
