name: Deploy SAP Timer Groovy demo
run-name: Deploy SAP Timer Groovy demo - ${{ inputs.operation }}-${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      operation:
        description: "Upload a new artifact or update an existing artifact"
        required: true
        default: upload
        type: choice
        options: [upload, update, deploy-only]
      version:
        description: "New CPI semantic version"
        required: true
        default: 1.0.1
        type: string

jobs:
  sdlc:
    uses: ./.github/workflows/sap-cpi-sdlc.yml
    with:
      manifest: config/SAP_TIMER_GROOVY_DEMO.yaml
      source: flows/SAP_TIMER_GROOVY_DEMO
      bundle: SAP_TIMER_GROOVY_DEMO.zip
      artifact_id: SAP_TIMER_GROOVY_DEMO
      operation: ${{ inputs.operation }}
      version: ${{ inputs.version }}
    secrets: inherit
